### PR TITLE
Added facade class docblock with static methods

### LINKED ISSUE #94: Facade @mixin should be replaced with @methods
The `@mixin` in the facade should presumably be at the class docblock level, rather than the method level. However, the methods in the main class are not static, whereas the facade methods will be.

Could we add `@method` attributes to a class level docblock, indicating the methods available, parameter and return types etc., based on the methods in the main class?

### PR DESCRIPTION
**Pull request by ariddlestone**
Closes #94

### CODE REVIEW

**Comment by ariddlestone** [comment]
Apologies - I need to move return types to before method name...

**Comment by Nielsvanpach** [comment]
Curious to hear which problem this solves for you! Is the `@mixin` not working?

**Comment by ariddlestone** [comment]
`ShortSchedule::command()` shows up as an unknown method in PhpStorm (among others), as the `@mixin` is not in the right place in `Spatie\ShortSchedule\Facades\ShortSchedule` (it's in the `ShortSchedule::getFacadeAccessor()` docblock, rather than the class docblock).

However, even when moved to the class docblock, tools still object to `command()` being called statically when it is not a static method. The change I've made follows the same pattern as `Illuminate\Support\Facades\Schedule`, which solves this problem by specifying the static methods in the Facade's class docblock.

**Comment by Nielsvanpach** [comment]
Thanks!

**Pull request merged**
